### DISCUSSION TITLE
Calculations or conditional statements in the script section

### DISCUSSION THREAD

**Discussion by wgronner** [RIKEN-RCCS/OpenComposer#6] [Q&A]
Hello everyone,

first of all, respect for this great software. This is exactly what OpenOndeman was missing.
It's amazing how much you can customize your workflow to create a job script.

But now to my question.
Is it possible to use calculations or conditional statements ( if-then-else ) within the script section? 

For example: 
if #queue = “small” then
  corepernode=20
  sel=ncores/corepernode 
else
  corepernode=40
  sel=ncores/corepernode 
endif

#PBS -l select=@sel:ncpus=ncores:mpiprocs=@corepernode

#PBS -l select=@sel:ncpus=ncores:mpiprocs=@corepernode

I hope I have been able to explain the situation to some extent.
Thank you for any assistance

**Comment by mnakao** [comment]
Dear @wgronner,

Thank you for your interest in Open Composer.

> Is it possible to use calculations or conditional statements ( if-then-else ) within the script section?

Yes, Open Composer generates purely shell scripts. However, since the #PBS directive is processed by the job scheduler before the shell is executed, you cannot write variables in the #PBS directive (this is a restriction of the job scheduler).

You can probably achieve what you want by writing the form.yml like this:

```
form:
  queue:
  widget: select
  label: Queue
  options:
    - [small, 20]
    - [large, 40]

script: |
  #PBS -l select=ncores/#{queue}:ncpus=ncores:mpiprocs=#{queue}
```
Thanks

**Reply by wgronner** [reply]
Hello mnakao,

thank you for your quick response.
I have tried out your suggestion.

_#PBS -l select=#{ncores}/#{queue}:ncpus=#{ncores}:mpiprocs=#{ncores}_

The following line is now generated. 
_#PBS -l select=**20/20**:ncpus=20:mpiprocs=20_

However, I was of the opinion that the following result would be generated
_#PBS -l select=**1**:ncpus=20:mpiprocs=20_

The calculation does not seem to be performed in the script section.
It just strings the text together

Have I overlooked something?


Thanks

**Reply by mnakao** [reply]
I understand what you want to do. You want to automatically calculate the number of nodes specified in the select directive. Unfortunately, Open Composer cannot perform calculations on variables assigned to it.

The user must manually calculate the number of nodes and the number of cores per node to be utilized as follows:
```
form:
  queue:
    widget: select
    label: Queue
    required: true
    options:
      - [small (20 MPI processes), 20, set-label-nodes_ncpus_2: Number of CPU cores per node (20 - 100), set-min-nodes_ncpus_2: 20, set-value-nodes_ncpus_2: 20]
      - [large (40 MPI processes), 40, set-label-nodes_ncpus_2: Number of CPU cores per node (40 - 100), set-min-nodes_ncpus_2: 40, set-value-nodes_ncpus_2: 40]

  nodes_ncpus:
    widget: number
    size: 2
    label: [Number of nodes (1 - 10), Number of CPU cores per node]
    value: [1, 1]
    min: [1, 1]
    max: [10, 100]
    step: [1, 1]
    required: [true, true]

script: |
  #PBS -l select=#{nodes_ncpus_1}:ncpus=#{nodes_ncpus_2}:mpiprocs=#{queue}
```
From your first post, it seems that the number of MPI processes is determined by the queue, so I set it in the `queue` widget. Also, since the number of MPI processes is equal to or less than the number of CPU cores to be reserved, I use the set-min directive to set the minimum value to be assigned to ncpus.

Currently, Open Composer can only do this, but I thought it would be useful to be able to perform simple calculations like you suggested. 

Best,
