### ISSUE TITLE
SSH Job submission failed

### ISSUE THREAD

**Issue by danxuZhang** [RIKEN-RCCS/OpenComposer#7]
Hi, I'm configuring my system with Open OnDemand and OpenComposer. 
I'm using a dedicated node for Open OnDemand and OpenComposer, and for submitting PBS Pro job, it will ssh to a login node and submit pbs job from there. 

I have configured OpenComposer as follows `/var/www/ood/apps/sys/OpenComposer/conf.yml.erb`:
``` yaml
---
# Required settings
apps_dir: "./apps"
scheduler: "pbspro"

# Optional settings
## General
#data_dir:  <%= ENV['HOME'] %>/composer
login_node: "sod-login01"
ssh_wrapper: "ssh sod-login01 "
# bin: "/usr/local/bin"
bin_overrides:
  qsub:     "/opt/pbs/bin/qsub"
  qstat:    "/opt/pbs/bin/qstat"
  qdel:     "/opt/pbs/bin/qdel"
```

When I click the submission button, the message shows:

> Job submission failed. (Job ID not found in output.) 

However, the job was indeed successfully submitted and I can check it from PBS Pro. 

I can manually submit the job with SSH: so it doesn't seem like an SSH connection issue. 

``` bash
[dzhang01@ood ~]$ ssh sod-login01 /opt/pbs/bin/qsub ~/job.sh
247.sod-pbs
``` 

Are there any logs or other tests can be done to debug the issue? Thanks!
